/**
 * Per-sport team-name normalization. Maps any known display variant to a
 * canonical lowercase token used for matching across data sources.
 *
 * If a team is missing here, the matcher falls back to lowercased exact match.
 * Add aliases when `edge resolve --grade` warns about unmatched games.
 */
const ALIASES: Record<string, Record<string, string>> = {
  mlb: {
    'arizona diamondbacks': 'diamondbacks',
    'atlanta braves': 'braves',
    'baltimore orioles': 'orioles',
    'boston red sox': 'red-sox',
    'chicago cubs': 'cubs',
    'chicago white sox': 'white-sox',
    'cincinnati reds': 'reds',
    'cleveland guardians': 'guardians',
    'colorado rockies': 'rockies',
    'detroit tigers': 'tigers',
    'houston astros': 'astros',
    'kansas city royals': 'royals',
    'los angeles angels': 'angels',
    'la angels': 'angels',
    'los angeles dodgers': 'dodgers',
    'la dodgers': 'dodgers',
    'miami marlins': 'marlins',
    'milwaukee brewers': 'brewers',
    'minnesota twins': 'twins',
    'new york mets': 'mets',
    'ny mets': 'mets',
    'new york yankees': 'yankees',
    'ny yankees': 'yankees',
    'oakland athletics': 'athletics',
    'philadelphia phillies': 'phillies',
    'pittsburgh pirates': 'pirates',
    'san diego padres': 'padres',
    'san francisco giants': 'giants',
    'sf giants': 'giants',
    'seattle mariners': 'mariners',
    'st. louis cardinals': 'cardinals',
    'st louis cardinals': 'cardinals',
    'tampa bay rays': 'rays',
    'texas rangers': 'rangers',
    'toronto blue jays': 'blue-jays',
    'washington nationals': 'nationals',
  },
  nba: {
    'atlanta hawks': 'hawks',
    'boston celtics': 'celtics',
    'brooklyn nets': 'nets',
    'charlotte hornets': 'hornets',
    'chicago bulls': 'bulls',
    'cleveland cavaliers': 'cavaliers',
    'dallas mavericks': 'mavericks',
    'denver nuggets': 'nuggets',
    'detroit pistons': 'pistons',
    'golden state warriors': 'warriors',
    'houston rockets': 'rockets',
    'indiana pacers': 'pacers',
    'la clippers': 'clippers',
    'los angeles clippers': 'clippers',
    'la lakers': 'lakers',
    'los angeles lakers': 'lakers',
    'memphis grizzlies': 'grizzlies',
    'miami heat': 'heat',
    'milwaukee bucks': 'bucks',
    'minnesota timberwolves': 'timberwolves',
    'new orleans pelicans': 'pelicans',
    'new york knicks': 'knicks',
    'ny knicks': 'knicks',
    'oklahoma city thunder': 'thunder',
    'orlando magic': 'magic',
    'philadelphia 76ers': '76ers',
    'phoenix suns': 'suns',
    'portland trail blazers': 'trail-blazers',
    'sacramento kings': 'kings',
    'san antonio spurs': 'spurs',
    'toronto raptors': 'raptors',
    'utah jazz': 'jazz',
    'washington wizards': 'wizards',
  },
  nhl: {
    'anaheim ducks': 'ducks',
    'arizona coyotes': 'coyotes',
    'boston bruins': 'bruins',
    'buffalo sabres': 'sabres',
    'calgary flames': 'flames',
    'carolina hurricanes': 'hurricanes',
    'chicago blackhawks': 'blackhawks',
    'colorado avalanche': 'avalanche',
    'columbus blue jackets': 'blue-jackets',
    'dallas stars': 'stars',
    'detroit red wings': 'red-wings',
    'edmonton oilers': 'oilers',
    'florida panthers': 'panthers',
    'los angeles kings': 'la-kings',
    'la kings': 'la-kings',
    'minnesota wild': 'wild',
    'montreal canadiens': 'canadiens',
    'nashville predators': 'predators',
    'new jersey devils': 'devils',
    'new york islanders': 'islanders',
    'ny islanders': 'islanders',
    'new york rangers': 'rangers-nhl',
    'ny rangers': 'rangers-nhl',
    'ottawa senators': 'senators',
    'philadelphia flyers': 'flyers',
    'pittsburgh penguins': 'penguins',
    'san jose sharks': 'sharks',
    'seattle kraken': 'kraken',
    'st. louis blues': 'blues',
    'st louis blues': 'blues',
    'tampa bay lightning': 'lightning',
    'toronto maple leafs': 'maple-leafs',
    'vancouver canucks': 'canucks',
    'vegas golden knights': 'golden-knights',
    'washington capitals': 'capitals',
    'winnipeg jets': 'jets',
  },
}

export function canonicalTeam(sport: string, displayName: string): string {
  const lower = displayName.toLowerCase().trim()
  return ALIASES[sport]?.[lower] ?? lower
}
